=== olgaBovkaniuk/homework/src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xsd"
           xmlns="src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xsd"
           elementFormDefault="qualified">
    <xs:element name="PurchaseOrder" type="PurchaseOrderType"/>
    <xs:complexType name="PurchaseOrderType">
        <xs:sequence>
            <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProductName" type="xs:string"/>
                        <xs:element name="Quantity" type="xs:positiveInteger"/>
                        <xs:element name="USPrice" type="xs:decimal"/>
                        <xs:element name="Comment" type="xs:string" minOccurs="0"/>
                        <xs:element name="ShipDate" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                    <xs:attribute name="PartNumber" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="OrderDate" type="xs:date"/>
    </xs:complexType>
</xs:schema>

=== olgaBovkaniuk/homework/src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xml
<?xml version="1.0"?>
<PurchaseOrder OrderDate="1999-10-20"
               xmlns="src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="src/com/gmail/olgabovkaniuk/controlWork2/purchaseOrder.xsd purchaseOrder.xsd">
    <Item PartNumber="872-AA">
        <ProductName>Lawnmower</ProductName>
        <Quantity>1</Quantity>
        <USPrice>148.95</USPrice>
        <Comment>Confirm this is electric</Comment>
    </Item>
    <Item PartNumber="926-AA">
        <ProductName>Baby Monitor</ProductName>
        <Quantity>1</Quantity>
        <USPrice>39.98</USPrice>
        <ShipDate>1999-05-21</ShipDate>
    </Item>
</PurchaseOrder>
